### PR TITLE
Added bStats metrics

### PR DESCRIPTION
**Pull request by DoNotSpamPls**
**When you want to merge this, please DM me on Discord (DoNotSpamPls#8787), so I can free up SkinsRestorer for you on bStats.org. I had taken it, because I was testing.**

NOTE: This has not been tested on anything apart from Spigot 1.12.2. I'd like testing.

I have also:
- bumped the version number to 13.1.5-BETA
- rewritten the config notes (shouldn't cause any issues with current users)
- fix the <<< HEAD thing in README.md
- fixed some more typos in the plugin 💯

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
Please do not merge yet, the plugin doesn't work on Sponge as of writing this. I'm working on a patch

**Comment by DoNotSpamPls** [comment]
I have talked with the bStats dev, and both of us don't know how to make Sponge metrics work (for now!!)
You can merge, I will make a new PR when I find how to do it 😛

**Comment by games647** [comment]
Sponge stats will be initialized by Guice (which is similar to `new MetricsSponge()`). So you just have to add a Metrics object field with Inject annotation. See this for reference: 

https://github.com/BtoBastian/bStats-Metrics/blob/master/bstats-sponge/src/examples/java/ExamplePlugin.java#L10-L11

**Comment by DoNotSpamPls** [comment]
We tried the @Inject function, and Sponge spews out some errors :(

**Comment by games647** [comment]
Make sure you import the correct inject class from guice

**Comment by DoNotSpamPls** [comment]
@games647 owo it works 😋 
Now we are just waiting for merge

**Comment by DoNotSpamPls** [comment]
Apparently I don't know how to use GitHub and the previous PRs were added to #214, so I'm closing the other 2 ones

**Pull request closed without merging**
