### PR TITLE
Mojang API -> MineTools

### PR DESCRIPTION
**Pull request by McLive**
Try this API to avoid 429 responses from Mojang.. Should solve lots of issues with unstable proxies.

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
Have you created the MineTools API? If so, can we fully trust it to work. We'll always put the Mojang API as a failsafe, but I'm just asking. Also, have you tested if this works with the plugin?

**Comment by McLive** [comment]
> Have you created the MineTools API? If so, can we fully trust it to work. We'll always put the Mojang API as a failsafe, but I'm just asking. Also, have you tested if this works with the plugin?

Yes and it fully works with the plugin.

> Also, we would much prefer if we could scrap proxies and third-party APIs (for the most part) and substiture them for caching. For example, you need to request the UUID of a player's username, and then you can store that in a cache. Hitting 600 requests for 10 minutes is highly unlikely, unless you have a server with thousands of players. The same thing could be applied for profiles.

Using MineTools, you wouldn't have to care much about caching, because it already does it for you (especially for simultaneous requests). You could store the results in a sqlite database or in a file for faster responses tho.

**Comment by DoNotSpamPls** [comment]
The thing is, I *really* don't want to use third-party APIs. SkinsRestorer used mcapi.ca back in the day, but at one moment the API shut down and suddenly everyone had glitchy behaviour. The perfect solution for us would be an SQLite database that caches the Mojang API results. That way we can only use the proxy in edge cases (or maybe drop proxy services entirely, and just give users the option to get proxies) and everyone else can just use the cached results

**Comment by xknat** [comment]
This will be tested first at out dev branch https://github.com/DoNotSpamPls/SkinsRestorerX/
for now closed

**Pull request closed without merging**
